version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrongPassword1!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    # healthcheck:
    #   test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrongPassword1!", "-Q", "SELECT 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  dacpac-deployer:
    build: .
    # depends_on:
    #   sqlserver:
    #     condition: service_healthy
    environment:
      SA_PASSWORD: "YourStrongPassword1!"
